"""Constants for Google Photos."""
from __future__ import annotations

DOMAIN = "google_photos"
MANUFACTURER = "Google, Inc."
DATA_AUTH = "auth"
DEFAULT_ACCESS = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/photoslibrary.readonly",
]

CONF_ALBUM_ID = "album_id"
CONF_ALBUM_ID_FAVORITES = "FAVORITES"

SETTING_IMAGESELECTION_MODE_RANDOM = "Random"
SETTING_IMAGESELECTION_MODE_ALBUM_ORDER = "Album order"
SETTING_IMAGESELECTION_MODE_OPTIONS = [
    SETTING_IMAGESELECTION_MODE_RANDOM,
    SETTING_IMAGESELECTION_MODE_ALBUM_ORDER,
]
SETTING_IMAGESELECTION_MODE_DEFAULT_OPTION = SETTING_IMAGESELECTION_MODE_RANDOM

SETTING_INTERVAL_OPTION_NONE = "Never"
SETTING_INTERVAL_OPTION_10 = "10 seconds"
SETTING_INTERVAL_OPTION_30 = "30 seconds"
SETTING_INTERVAL_OPTION_60 = "60 seconds"
SETTING_INTERVAL_OPTION_120 = "120 seconds"
SETTING_INTERVAL_OPTION_300 = "300 seconds"
SETTING_INTERVAL_OPTIONS = [
    SETTING_INTERVAL_OPTION_NONE,
    SETTING_INTERVAL_OPTION_10,
    SETTING_INTERVAL_OPTION_30,
    SETTING_INTERVAL_OPTION_60,
    SETTING_INTERVAL_OPTION_120,
    SETTING_INTERVAL_OPTION_300,
]
SETTING_INTERVAL_DEFAULT_OPTION = SETTING_INTERVAL_OPTION_60
SETTING_INTERVAL_MAP = dict(
    {
        SETTING_INTERVAL_OPTION_NONE: None,
        SETTING_INTERVAL_OPTION_10: 10,
        SETTING_INTERVAL_OPTION_30: 30,
        SETTING_INTERVAL_OPTION_60: 60,
        SETTING_INTERVAL_OPTION_120: 120,
        SETTING_INTERVAL_OPTION_300: 300,
    }
)

CONF_WRITEMETADATA = "attribute_metadata"
WRITEMETADATA_DEFAULT_OPTION = False

SETTING_CROP_MODE_ORIGINAL = "Original"
SETTING_CROP_MODE_CROP = "Crop"
SETTING_CROP_MODE_COMBINED = "Combine images"
SETTING_CROP_MODE_OPTIONS = [
    SETTING_CROP_MODE_ORIGINAL,
    SETTING_CROP_MODE_CROP,
    SETTING_CROP_MODE_COMBINED,
]
SETTING_CROP_MODE_DEFAULT_OPTION = SETTING_CROP_MODE_ORIGINAL
